### PR TITLE
angler: Swap left with right fingerprint gestures

### PR DESCRIPTION
**Pull request by tr1gg3rman**
This is a fix for when the device is held in landscape mode the fingerprint
swipe gestues are reversed. You have to swipe up for down and down for up.

### CODE REVIEW

**Comment by Lennartwieboldt** [comment]
I'm not sure what you did here but we don't accept pull requests on GitHub. Please upload the change to our Gerrit if you want to contribute to aospa

**Comment by tr1gg3rman** [comment]
My apologies, I wasn't aware. I was just trying to add a fix for the Angler. I'll attempt to upload it to your gerrit. Respectfully, tr1gg3r.man12:38, August 29, 2017, Lennart Wieboldt <notifications@github.com>:I'm not sure what you did here but we don't accept pull requests on GitHub. Please upload the change to our Gerrit if you want to contribute to aospa

**Comment by tr1gg3rman** [comment]
Can you tell me what part of this command I'm typing in wrong? git clone ssh://tr1gg3rman@gerrit.aospa.co:29418/manifest.gitI get the following errors :fatal: Project could not be found: manifestfatal: Could not read from remote repository Thanks in advance, ~tr1gg3r.man 12:38, August 29, 2017, Lennart Wieboldt <notifications@github.com>:I'm not sure what you did here but we don't accept pull requests on GitHub. Please upload the change to our Gerrit if you want to contribute to aospa

**Comment by Lennartwieboldt** [comment]
https://gerrit.aospa.co/#/c/3862/

**Pull request closed without merging**
